version: "3.9"

services:
  db:
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_dev:/var/lib/postgresql/data
    ports:
      - "1234:5432"

volumes:
  db_dev:
